spring:
  message: Hello, Namaste
#  profiles:
#    active: prod

server:
  port: 8080

# key's format could be any: smallcase, hi-phen, snakecase
kabita:
  common:
    best-food: RICE
    best-drink: soda
    bestAcharPickle: lapsi ko aachar
    bestcountryworld: switzerland
    best_color_rainbow: yellow